name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

